### ISSUE TITLE
Failed to build when compiling wasmedge-sys v0.12.2

### ISSUE THREAD

**Issue by aetiurf** [containerd/runwasi#101]
## Description

When I run `make` in root direction, it failed in the step to compile wasmedge-sys v0.12.2, and the error is here:

```plain
The following warnings were emitted during compilation:

warning: [wasmedge-sys] Failed to locate lib_dir, include_dir, or header.

error: failed to run custom build command for `wasmedge-sys v0.12.2`

Caused by:
  process didn't exit successfully: `/home/vagrant/runwasi/target/debug/build/wasmedge-sys-1a654059db2210f1/build-script-build` (exit status: 101)
  --- stdout
  cargo:warning=[wasmedge-sys] Failed to locate lib_dir, include_dir, or header.

  --- stderr
  thread 'main' panicked at '[wasmedge-sys] Failed to locate the required header and/or library file. Please reference the link: https://wasmedge.org/book/en/embed/rust.html', /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmedge-sys-0.12.2/build.rs:30:25
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:19: build] Error 101
```

Did I miss something?

## Expected

Build successfully.

## Environment

Ubuntu 20.04.6 LTS

**Comment by aetiurf** [comment]
Update:
In my host the WasmEdge has been already installed.

```plain
ls -l /usr/local/lib/libwasmedge.so
lrwxrwxrwx 1 root root 16 Mar 27 10:05 /usr/local/lib/libwasmedge.so -> libwasmedge.so.0
```

**Comment by apepkuss** [comment]
@aetiurf The `/usr/local/lib` and `/usr/local/include/wasmedge` look like below on my side. Could you please check them on your side?

```bash
root@0a877562f39e:/usr/local/lib# ll
total 5060
drwxr-xr-x 1 root root     4096 Apr  4 04:32 ./
drwxr-xr-x 1 root root     4096 Nov  7  2021 ../
lrwxrwxrwx 1 root root       16 Apr  4 04:32 libwasmedge.so -> libwasmedge.so.0
lrwxrwxrwx 1 root root       20 Apr  4 04:32 libwasmedge.so.0 -> libwasmedge.so.0.0.1
-rw-r--r-- 1 root root  5147272 Apr  4 04:30 libwasmedge.so.0.0.1
drwxrwsr-x 4 root staff    4096 Apr 18  2022 python2.7/
drwxr-xr-x 1 root root     4096 Dec 15  2021 python3.9/
drwxr-xr-x 2 root root     4096 Apr  4 04:32 wasmedge/

root@0a877562f39e:/usr/local/include/wasmedge# ll
total 204
drwxr-xr-x 2 root root   4096 Apr  4 04:32 ./
drwxr-xr-x 1 root root   4096 Apr  4 04:32 ../
-rw-r--r-- 1 root root  33558 Apr  4 04:23 enum.inc
-rw-r--r-- 1 root root   2109 Apr  4 04:23 enum_configure.h
-rw-r--r-- 1 root root    976 Apr  4 04:23 enum_errcode.h
-rw-r--r-- 1 root root   1592 Apr  4 04:23 enum_types.h
-rw-r--r-- 1 root root    834 Apr  4 02:55 int128.h
-rw-r--r-- 1 root root    768 Apr  4 04:23 version.h
-rw-r--r-- 1 root root 141510 Apr  4 02:55 wasmedge.h
```

Besides, you can follow the instructions in [Installation and Uninstallation](https://wasmedge.org/book/en/quick_start/install.html) to deploy WasmEdge.

**Comment by aetiurf** [comment]
> @aetiurf The `/usr/local/lib` and `/usr/local/include/wasmedge` look like below on my side. Could you please check them on your side?
> 
> ```shell
> root@0a877562f39e:/usr/local/lib# ll
> total 5060
> drwxr-xr-x 1 root root     4096 Apr  4 04:32 ./
> drwxr-xr-x 1 root root     4096 Nov  7  2021 ../
> lrwxrwxrwx 1 root root       16 Apr  4 04:32 libwasmedge.so -> libwasmedge.so.0
> lrwxrwxrwx 1 root root       20 Apr  4 04:32 libwasmedge.so.0 -> libwasmedge.so.0.0.1
> -rw-r--r-- 1 root root  5147272 Apr  4 04:30 libwasmedge.so.0.0.1
> drwxrwsr-x 4 root staff    4096 Apr 18  2022 python2.7/
> drwxr-xr-x 1 root root     4096 Dec 15  2021 python3.9/
> drwxr-xr-x 2 root root     4096 Apr  4 04:32 wasmedge/
> 
> root@0a877562f39e:/usr/local/include/wasmedge# ll
> total 204
> drwxr-xr-x 2 root root   4096 Apr  4 04:32 ./
> drwxr-xr-x 1 root root   4096 Apr  4 04:32 ../
> -rw-r--r-- 1 root root  33558 Apr  4 04:23 enum.inc
> -rw-r--r-- 1 root root   2109 Apr  4 04:23 enum_configure.h
> -rw-r--r-- 1 root root    976 Apr  4 04:23 enum_errcode.h
> -rw-r--r-- 1 root root   1592 Apr  4 04:23 enum_types.h
> -rw-r--r-- 1 root root    834 Apr  4 02:55 int128.h
> -rw-r--r-- 1 root root    768 Apr  4 04:23 version.h
> -rw-r--r-- 1 root root 141510 Apr  4 02:55 wasmedge.h
> ```
> 
> Besides, you can follow the instructions in [Installation and Uninstallation](https://wasmedge.org/book/en/quick_start/install.html) to deploy WasmEdge. Notice that `wasmedge-sys 0.12.2` depends on `WasmEdge 0.11.2` according to the [versioning table](https://crates.io/crates/wasmedge-sys).

I built WasmEdge from source and now find that the directory "/u/l/lib/wasmedge/" was not installed correctly.
Thanks a lot!
