### ISSUE TITLE
tar.gz files included in releases are empty

### ISSUE THREAD

**Issue by mrhockeymonkey** [containerd/runwasi#109]
It looks like the `tar.gz` assets included in releases are empty. I tried to look at why this might be but im not familiar with the github actions syntax and its hard to test locally. I resorted to building from source but I assume these were meant to have the pre-built binaries in them?

**Comment by cpuguy83** [comment]
Those should not have any release assets.
See https://github.com/containerd/runwasi/pull/86

We'll get that merged in before we tag anything new.
