### ISSUE TITLE
Use youki libcontainer crate for Wasmtime shim

### ISSUE THREAD

**Issue by ipuustin** [containerd/runwasi#110]
The work to enable youki libcontainer support for WasmEdge shim was done in https://github.com/containerd/runwasi/pull/78. Do a similar integration also for Wasmtime.

**Comment by utam0k** [comment]
I can find the time to do it, so you may assign it to me.

**Comment by Mossaka** [comment]
@utam0k is it okay if I assign this task to myself?

**Comment by utam0k** [comment]
@Mossaka Sure!
