### ISSUE TITLE
WasmEdge can run only 254 instances?

### ISSUE THREAD

**Issue by ipuustin** [containerd/runwasi#120]
If I add a unit tests which creates, runs, waits and deletes a WasmEdge instance for 300 times, the test fails on the 255th run:

```
...
...
...
Running test iteration 253
Running test iteration 254
Running test iteration 255
Error: Any(failed to create container

Caused by:
    0: failed to wait for init ready
    1: failed to wait for init ready
    2: channel connection broken)


failures:
    instance::wasitest::test_wasi_300
```

It feels to me that we are leaking some resource (such as file descriptors), but I don't know if the problem is in WasmEdge, libcontainer or runwasi (or in the test setup :-). This is the test:

```diff
diff --git a/crates/containerd-shim-wasmedge/src/instance.rs b/crates/containerd-shim-wasmedge/src/instance.rs
index 87d0148..31a8e67 100644
--- a/crates/containerd-shim-wasmedge/src/instance.rs
+++ b/crates/containerd-shim-wasmedge/src/instance.rs
@@ -472,6 +472,32 @@ mod wasitest {
         Ok(())
     }

+    #[test]
+    #[serial]
+    fn test_wasi_300() -> Result<(), Error> {
+        if !has_cap_sys_admin() {
+            println!("running test with sudo: {}", function!());
+            return run_test_with_sudo(function!());
+        }
+
+        for i in 1..300 {
+            println!("Running test iteration {}", i);
+
+            let wasmbytes = wat2wasm(WASI_HELLO_WAT).unwrap();
+            let dir = tempdir()?;
+            let path = dir.path();
+            let res = run_wasi_test(&dir, wasmbytes)?;
+
+            assert_eq!(res.0, 0);
+
+            let output = read_to_string(path.join("stdout"))?;
+            assert_eq!(output, "hello world\n");
+
+            reset_stdio();
+        }
+        Ok(())
+    }
+
     #[test]
     #[serial]
     fn test_wasi_error() -> Result<(), Error> {
```

**Comment by ipuustin** [comment]
@utam0k have you ever encountered these errors in Youki?

**Comment by utam0k** [comment]
Hmm, I don't know. I recommend using bpftrace to investigate this problem.

https://github.com/containers/youki/blob/9e1b769294e2b82fabfa6be17f65b752abf50f90/Makefile#L123-L125

Before running it, please update the version of the libcontainer

**Comment by ipuustin** [comment]
Thanks @utam0k, that script was a good tip. I modified it a bit to track also `close()´ calls in Youki and runwasi.

It seems to me that we are indeed having too much open file descriptors, and finally an `open()` call fails within Youki init process (errno 24). It seems that the leaked file descriptors are coming from the runwasi. At least one `open()` call which doesn't have a corresponding `close()` is done to the `stdout` file in the tmp directory which contains the rootfs directory.

This is the log:
https://gist.github.com/ipuustin/d42ba1ae389263e8c6ebeb16725a66db

**Comment by ipuustin** [comment]
Looks like there are two classes of leaks:
1. The raw stdio FDs need to be closed after they are passed to the container process. https://github.com/containerd/runwasi/pull/121 should fix that.
2. Youki internal communication channels were not fully closed. https://github.com/containers/youki/pull/1936 closes the channel receiving ends.

Because we were leaking four fds for every container, we were only hitting 254 test iterations (since the default open file limit appears to be 1024).

**Comment by ipuustin** [comment]
Closing this now since both PRs are merged and there's nothing to do before next libcontainer-rs release.
