### ISSUE TITLE
wasmedge shim fails with some entry points

### ISSUE THREAD

**Issue by jprendes** [containerd/runwasi#143]
The following commands fail:
```
docker run --rm --platform wasi/wasm --runtime io.contaierd.wasmedge.v1 secondstate/rust-example-hello:latest
docker run --rm --platform wasi/wasm --runtime io.contaierd.wasmedge.v1 --entrypoint hello.wasm secondstate/rust-example-hello:latest
```

while the following commands succeed:
```
docker run --rm --platform wasi/wasm --runtime io.contaierd.wasmedge.v1 --entrypoint /hello.wasm secondstate/rust-example-hello:latest
docker run --rm --platform wasi/wasm --runtime io.contaierd.wasmedge.v1 --entrypoint ./hello.wasm secondstate/rust-example-hello:latest
```

The `secondstate/rust-example-hello:latest` specifies its entrypoint as `["hello.wasm"]`.

The same 4 commands succeed with the `io.containerd.wasmtime.v1` runtime.

**Comment by jprendes** [comment]
After some debugging, I'm inclined to think that this is the right behavior for the wasmedge shim and the problem should be fixed in `secondstate/rust-example-hello` instead.

This was introduced by the use of `youki` in wasmedge. When `youki` creates the main process, it checks that the entrypoint is in `PATH` and is executable, see [verify_binary](https://github.com/containers/youki/blob/fe7e7ac11e827c738b451e44af0bc6ce26055cf0/crates/libcontainer/src/process/container_init_process.rs#L104).

This follows the same behavior as for a standard linux container, e.g.,
```
docker run --rm --entrypoint=hello hello-world  # --> fails
docker run --rm --entrypoint=/hello hello-world # --> works
```

The following command does work
```
docker run --rm --platform wasi/wasm --runtime io.contaierd.wasmedge.v1 -e=PATH=/ secondstate/rust-example-hello:latest
```

**Comment by jsturtevant** [comment]
@jprendes I think you were write that there was a difference between wasmtime and wasmedge.  Your fix to the example works but in wasmtime we append the module to the path: 

https://github.com/containerd/runwasi/blob/aeb48cd053f0b1049ae59f8ce4de8a8505fde85d/crates/containerd-shim-wasmtime/src/instance.rs#L134-L137

but in wasmedge:

That doesn't happen: https://github.com/containerd/runwasi/blob/aeb48cd053f0b1049ae59f8ce4de8a8505fde85d/crates/containerd-shim-wasmedge/src/executor.rs#L30-L33
