### ISSUE TITLE
Patch version updates automated by Dependabot

### ISSUE THREAD

**Issue by utam0k** [containerd/runwasi#150]
How about making patch version updates automatically merged when CI passes?

**Comment by Mossaka** [comment]
Actually, this might be undesired as we have PRs like https://github.com/containerd/runwasi/pull/113 passed the CI but we didn't want to merge it to the main branch.

**Comment by utam0k** [comment]
> Actually, this might be undesired as we have PRs like #113 passed the CI but we didn't want to merge it to the main branch.

@Mossaka Thanks for your feedback. Only a **PATCH** version is planned. That is a minor version release, correct?

**Comment by Mossaka** [comment]
See discussion on #188
