### ISSUE TITLE
CI failed at wasmedge shim's integration tests

### ISSUE THREAD

**Issue by Mossaka** [containerd/runwasi#152]
It looks like the CI has failed for WasmEdge shim's integration tests. See an instance [here](https://github.com/containerd/runwasi/actions/runs/5327073669/jobs/9650127428?pr=151)

**Comment by jsturtevant** [comment]
same here: https://github.com/containerd/runwasi/pull/153

**Comment by ipuustin** [comment]
It seems that https://github.com/containerd/runwasi/pull/111 built fine today... I wonder if the 90s timeout is sometimes too short?

**Comment by jsturtevant** [comment]
maybe, not sure why it seems to only flake on 22.04?

**Comment by jprendes** [comment]
This also seems to affect the wasmtime shim [here](https://github.com/containerd/runwasi/actions/runs/5536647363/jobs/10104716972?pr=175)

**Comment by jprendes** [comment]
I wonder is this is the same as https://github.com/containerd/runwasi/issues/70 and running the container is just hanging

**Comment by Mossaka** [comment]
Umm another instance: https://github.com/containerd/runwasi/actions/runs/5545507419/jobs/10124726842?pr=156

**Comment by jprendes** [comment]
another instance with wasmtime https://github.com/containerd/runwasi/actions/runs/5614458631/job/15212731257#step:6:2443

**Comment by Mossaka** [comment]
Replaced by issue #322
