### ISSUE TITLE
Instance::new should return a Result type

### ISSUE THREAD

**Issue by Mossaka** [containerd/runwasi#158]
This was discussed before: https://github.com/containerd/runwasi/pull/54#issuecomment-1403269766

IMHO we should aim to remove as many `unwrap()` calls as possible from shim "main thread", because a library should not panic easily.

_Originally posted by @ipuustin in https://github.com/containerd/runwasi/pull/142#discussion_r1238411469_

**Comment by cpuguy83** [comment]
I seem to recall this causes issues with the type being unsized.
