### ISSUE TITLE
docker run with wasmedge shim stop working #81

### ISSUE THREAD

**Issue by CaptainVincent** [containerd/runwasi#163]
## Issue Highlight

- Test below command fail due to `c2c2d0d98237e297e72cbcf9c695a4a215a39bad` #81
```sh
docker run --rm --runtime=io.containerd.wasmedge.v1 --platform wasi/wasm jorgeprendes420/wasmtest echo 'hello'
```
> Fail commit need run with wasmedge 0.12.1

- [x] Test below command fail due to `ca5260fd34635ca56d81db3f59ee8672fc7fde68 ` #78
```sh
git clone https://github.com/WasmEdge/wasmedge_hyper_demo.git
cd wasmedge_hyper_demo
docker compose up client
```
> Fail commit need run with older wasmedge 0.11.2
> **[Update]**
> The shim now requires the entrypoint path to be resolved using normal posix executable resolution now.
> so ENTRYPOINT need start with `/` is the new usage restrictions and add padding `/` in path could resolve the second one.

## Motivation
Due to the plan of deprecating the fork under [Second State](https://github.com/second-state/runwasi), I need to conduct an evaluation of the current functionality of containerd/runwasi before proceeding. I have discovered that using the wasmedge runtime with Docker has been broken for quite some time (all testing while ctr is working fine). Here, I am providing a [document](https://hackmd.io/myzQNXzXRL6_-j92CPO-2Q?view) that includes the codebase and process I have been using to test docker run.

**Comment by jprendes** [comment]
I've identified the underlying issue in `containerd-shim` and created an upstream PR: https://github.com/containerd/rust-extensions/pull/151
Once that's merged upstream we need to bump the `containerd-shim` dependency here. This will also require bumping the `ttrpc` dependency to `0.8.0`.

We should also add a test to make sure we catch these kind of issues.
