### ISSUE TITLE
make build encountered an error

### ISSUE THREAD

**Issue by dierbei** [containerd/runwasi#169]
I tried to use the `make build` command and got the following error:

![image](https://github.com/containerd/runwasi/assets/52097565/01cdcd64-d87f-4867-bbb9-93202266f0ae)

I think this error may have occurred when installing wasmedge. 

I tried to use the official command: `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all -v 0.12.1
`, and the `make build` was executed successfully.

Now it looks like make bin/wasmedge doesn't install the required dependencies.

**Comment by GQQQy** [comment]
yes, I met the same err. I also used the cmd `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all -v 0.12.1`, and then set `sudo -E sh -c 'echo "$(PWD)/bin/wasmedge/lib" > /etc/ld.so.conf.d/libwasmedge.conf' && sudo ldconfig`. 
同学，你这个方法不错 :)

**Comment by dierbei** [comment]
I want to try to fix this error later, can you give me some advice?

**Comment by jprendes** [comment]
After installing WasmEdge, and before running `make` you need to set  `WASMEDGE_INCLUDE_DIR` and `WASMEDGE_LIB_DIR`.
Please try the following:
```
make bin/wasmedge
export WASMEDGE_INCLUDE_DIR=$PWD/bin/wasmedge/include
export WASMEDGE_LIB_DIR=$PWD/bin/wasmedge/lib
make build
```

We could either document this beter of improve the makefile to take care of this automatically.

**Comment by dierbei** [comment]
@jprendes Thanks for your suggestion.

I modified the following two places:
1. make build
2. make check
