### ISSUE TITLE
Add more checks like validating protos to CI

### ISSUE THREAD

**Issue by Mossaka** [containerd/runwasi#191]
_Originally posted by @cpuguy83 in https://github.com/containerd/runwasi/issues/188#issuecomment-1644680009_

**Comment by jsturtevant** [comment]
I believe this was resoved with https://github.com/containerd/runwasi/pull/81 since the build now includes `generate_bindings`

https://github.com/containerd/runwasi/blob/2dbde802a52363b8e9bba3c1ed95fe6231dfc8ca/Makefile#L17-L20

**Comment by Mossaka** [comment]
It looks like #81 have resolved this issue.
