### ISSUE TITLE
CI might be broken after #187

### ISSUE THREAD

**Issue by jsturtevant** [containerd/runwasi#193]
seems like CI might be broken after #187 

```
   Dirty wasmedge-sys v0.15.0: the file `/usr/lib/llvm-14/lib/clang/14.0.0/include/stdbool.h` is missing
   Compiling wasmedge-sys v0.15.0
     Running `/home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build`
error: failed to run custom build command for `wasmedge-sys v0.15.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build` (exit status: 1)
  --- stderr
  /home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build)
  /home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build)
  /home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build)
warning: build failed, waiting for other jobs to finish...
````

_Originally posted by @jsturtevant in https://github.com/containerd/runwasi/issues/192#issuecomment-1646270928_

**Comment by jsturtevant** [comment]
this also failed in https://github.com/containerd/runwasi/pull/189 even though it merged https://github.com/containerd/runwasi/actions/runs/5605270172/job/15185629841

**Comment by jsturtevant** [comment]
and is failing in #147 after rebasing

**Comment by jsturtevant** [comment]
@jprendes any ideas?

**Comment by jprendes** [comment]
It's odd, it did build fine in #187.
From this error
```
/home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/work/runwasi/runwasi/target/debug/build/wasmedge-sys-24c4a5d29523e79f/build-script-build)
```
The buildscript seems to be compiled with a newer glibc than the one in the system. But normally the build script is compiled locally.
It makes me think that Ubuntu 20.04 is trying to use the cache from Ubuntu 22.04.

Can you try adding back the cache removed in #189 and try again?

**Comment by jprendes** [comment]
The CI in #189 failed 2 days ago before #187 was merged.
I also failed with `wasmedge-sys` `0.14.0`, while #189 bumped it to `0.15.0`.
It further makes me think it's a cache issue.

**Comment by jsturtevant** [comment]
added the cache bits back in https://github.com/containerd/runwasi/pull/192 and still failing 🤷 . will look again with fresh eyes next week

**Comment by jsturtevant** [comment]
> The CI in #189 failed 2 days ago before #187 was merged.

good catch, something else is going on....

**Comment by jsturtevant** [comment]
verified that isn't related to any of the code changes: https://github.com/containerd/runwasi/pull/195 with failed run https://github.com/containerd/runwasi/actions/runs/5627640566/job/15250472538?pr=195

**Comment by jprendes** [comment]
Here you can see in #195 that both ubuntu 20.04 ans 22.04 are using the same cache:
* ubuntu 20.04 cache key [v0-rust-build-e5fbe2f0-8b9d9bd6](https://github.com/containerd/runwasi/actions/runs/5627640566/job/15250472538?pr=195#step:4:209)
* ubuntu 22.04 cache key [v0-rust-build-e5fbe2f0-8b9d9bd6](https://github.com/containerd/runwasi/actions/runs/5627640566/job/15250472637?pr=195#step:4:209)
