### ISSUE TITLE
Adapt youki executors when upgrading libcontainer

### ISSUE THREAD

**Issue by 0xE282B0** [containerd/runwasi#209]
Youki has changed the way executors are created. The new method is to create a `get_executor()` function that returns an Executor. The executors in the youki crate can be used as an example: https://github.com/containers/youki/blob/main/crates/youki/src/workload
Instead of the `can_handle()` function, the executor now returns an `ExecutorError::CantHandle(EXECUTOR_NAME)` error, which is then handled explicitly like this https://github.com/containers/youki/blob/main/crates/youki/src/workload/executor.rs#L18-L23. This gives more control over the order in which executors are tried.

We need to adapt our executors before upgrading to latest libcontainer version.

**Comment by Mossaka** [comment]
I can take this one

**Comment by utam0k** [comment]
cc: @yihuaf 👀

**Comment by yihuaf** [comment]
@Mossaka Would you mind assign this to me so I can help take care of this? This is also a good exercise for me to understand the ergonomics of the libcontainer apis.

**Comment by Mossaka** [comment]
Sure!

**Comment by 0xE282B0** [comment]
@yihuaf runwasi now uses libcontainer 0.2. Is there anything else to do here, or can we close this issue?

**Comment by Mossaka** [comment]
Nope we can close it now
