### ISSUE TITLE
thiserror and anyhow

### ISSUE THREAD

**Issue by rumpl** [containerd/runwasi#25]
This project uses two libraries for error handling, maybe we can choose only one and remove the other? I'm not sure why both are needed. If I had to choose I would keep `anyhow`, I like their `context` function. WDYT?

**Comment by Mossaka** [comment]
`anyhow` sounds good to me.

**Comment by cpuguy83** [comment]
I find the use cases for these to be different.
Anyhow creates generic errors, thiserror provides a macros for creating strongly typed errors.
