### ISSUE TITLE
Consolidate shim testing

### ISSUE THREAD

**Issue by jprendes** [containerd/runwasi#269]
We are currently testing `[ wasmedge ] × [ k3s ] × [ Ubuntu 20.04, Ubuntu 22.04 ]` and `[ wasmtime ] × [ kind ] × [ Ubuntu 20.04, Ubuntu 22.04 ]`.
I propose we expand this to `[ wasmedge, wasmtime ] × [ k3s, kind ] × [ Ubuntu 20.04, Ubuntu 22.04 ]`.
This leas to the questions
* Is there value in testing `[ k3s, kind ]` ?
  - Should  we keep just one of them?
* Is there value in testing `[ Ubuntu 20.04, Ubuntu 22.04 ]` ?
  - The shim is actually running within a vm / container. This config changes the host OS, which IIUC is not very relevant to the shims.
  - In the `k3s` case the shim is built in the host OS, so there might be some limited value.

**Comment by jsturtevant** [comment]
> Is there value in testing [ k3s, kind ] ?
Should we keep just one of them?

I am not sure if there is a reason both were added but I would think we would only need one.  `kind` is used pretty heavily in kubernetes test suites upstream

> The shim is actually running within a vm / container

Is it? Typically, the shim runs on the kubernetes node of the machine next to containerd

**Comment by jprendes** [comment]
> Is it? Typically, the shim runs on the kubernetes node of the machine next to containerd

IIUC, the node in kind are container images (as far as I can tell based on ubuntu), and in kind they are vm based (way less sure about k3s)
