### ISSUE TITLE
Add wasmer support

### ISSUE THREAD

**Issue by dierbei** [containerd/runwasi#275]
I recently tried `wasmer` to run `wasm`. it seems to work pretty well.

I'd like to try to add [wasmer](https://github.com/wasmerio/wasmer) support.

**Comment by 0xE282B0** [comment]
When you're interested, I would have a PR ready: https://github.com/0xE282B0/runwasi/pull/3

**Comment by dierbei** [comment]
@0xE282B0 Wow, looking forward to trying it out.

**Comment by 0xE282B0** [comment]
If it is what you are looking for, we can open a PR. Since you have experience in Wasmer, I'd appreciate if you could do a review 😊

**Comment by dierbei** [comment]
@0xE282B0 I'm actually a newbie when it comes to this, but I'm happy to be involved in this.

I will open a `PR`.

**Comment by 0xE282B0** [comment]
Hi @dierbei,

Regarding https://github.com/containerd/runwasi/pull/281#discussion_r1309208950, I have described a test case for the wasix-axum example. I hope it is easy to reproduce.

### Preparing the image

This test uses the [wasix-axum](https://github.com/wasix-org/wasix-rust-examples/tree/main/wasix-axum) example from the `wasix-rust-examples` repository. It is built on the host and packaged into a Docker image.

```sh
cargo install cargo-wasix
cargo wasix build --release 

cat > Dockerfile.t <<EOF
FROM scratch
COPY --chmod=0755 target/wasm32-wasmer-wasi/release/wasix-axum.wasm /wasix-axum.wasm
ENTRYPOINT ["/wasix-axum.wasm"]
EOF

docker  build . -t 0xe282b0/wasix-axum --push
```
The Docker image [0xe282b0/wasix-axum](https://hub.docker.com/r/0xe282b0/wasix-axum/tags) is publicly available an can be used for testing.


### Test setup
```sh
# (optional) open the containerd logs in a separate terminal
journalctl -fu containerd
# load the image into containerd
sudo ctr i pull docker.io/0xe282b0/wasix-axum:latest
# replace the runtime_path to your shim location
# run the example
sudo ctr run --rm --runtime=/home/e282b0.linux/runwasi/dist/bin/containerd-shim-wasmer-v1 --net-host --env PORT=3000 docker.io/0xe282b0/wasix-axum:latest wasix-test /wasix-axum.wasm
# observe the containerd log (may take up to one minute)
```

### Expected output
```sh
# Container output:
# Listening on http://127.0.0.1:3000

curl localhost:3000
# Hello, Axum ❤️ WASIX!
```

### Actual output (in containerd log)
```sh
 [INFO] waiting for instance: wasmer-1
 [INFO] wasmer executor exec method
 [INFO] setting up wasi
 [INFO] wasi context ready
 [INFO] loading module from file wasix-axum.wasm
 [INFO] Starting `tokio` runtime...
 [INFO] Creating `WasiEnv`.... args: ["/wasix-axum.wasm"], envs: [("PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"), ("PORT", "3000"), ("HOSTNAME", "lima-default")]
 [INFO] Instantiating module with WASI imports...
 [ERROR] failed to execute workload err=Other("failed to start wasm: Error while importing \"wasi_snapshot_preview1\".\"fd_fdstat_get\": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [I32] })") name="wasmer"
 [ERROR] failed to execute payload err=ExecutionFailed { source: Other("failed to start wasm: Error while importing \"wasi_snapshot_preview1\".\"fd_fdstat_get\": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [I32] })"), name: "wasmer" }
 [ERROR] failed to initialize container process: failed executor wasmer
```

It seems [fd_fdstat_get](https://wasix.org/docs/api-reference/wasi/fd_fdstat_get) is missing, but it should be part of WASI. 🤔

**Comment by dierbei** [comment]
@0xE282B0 You and I are thinking the same thing.

I want to be able to use `container` to run `wasm`.

A step further is in `k8s`. I think the problem might be due to the need to add some `flags`.

I will test it and wait for my good news.

**Comment by dierbei** [comment]
I'll run some more tests

**Comment by 0xE282B0** [comment]
@dierbei, awesome job, thanks for patiently making all the requested changes.
Well done!
