### ISSUE TITLE
Walkaround on libcontainer's verify_binary

### ISSUE THREAD

**Issue by Mossaka** [containerd/runwasi#278]
While issue https://github.com/containers/youki/issues/2220 is on-going to make `verify_binary` optional, is there a way to walkaround the requirement for an entrypoint to be an executable here? This is needed to make `containerd-wasm-shims` use the existing images which use "/" as the entrypoint.

**Comment by jprendes** [comment]
IIUC, that's already fixed with https://github.com/containers/youki/pull/2258.
We just need a new youki release (or using a git rev)

**Comment by utam0k** [comment]
Are you waiting for release?

**Comment by jprendes** [comment]
A release would be great.
