### ISSUE TITLE
v1 cgroup feature is required, but was not enabled during compile time

### ISSUE THREAD

**Issue by 0xE282B0** [containerd/runwasi#288]
Hi,
I tried the spin shim from master and when I try to run it on [`colima`](https://github.com/abiosoft/colima) with `kind` I get the following error:

```sh
Error: failed to start containerd task "spin-hello": 
  Others("failed to create container: v1 error: 
    v1 cgroup feature is required, but was not enabled during compile time"): unknown
```

Is something blocking us from enabling V1 croup?

**Comment by thangchung** [comment]
I ran spin shim on k3d from master and used docker on Ubuntu 22.02 and had got the same problem 

```bash
13s         Warning   Failed                    pod/wasm-spin-7bc59d855b-p85lq       Error: failed to start containerd task "spin-hello": Others("failed to create container: v1 error: v1 cgroup feature is required, but was not enabled during compile time"): unknown
12s         Warning   BackOff                   pod/wasm-spin-7bc59d855b-p85lq       Back-off restarting failed container
```

**Comment by Mossaka** [comment]
@thangchung do you have a link to the repo that contains spin application / image, and a workflow yaml file?

**Comment by thangchung** [comment]
@Mossaka The code is at https://github.com/thangchung/dapr-labs/blob/feat/spin-refactor/polyglot/iac/kind-spin/product-api-deploy.yaml

But I think my problem is that wsl2 - Ubuntu 22 with cgroup v2 enabled does not work well, still figured it out by searching issues around on the wsl2 repo.

**Comment by 0xE282B0** [comment]
Excellent, that will help windows users a lot!

**Comment by 0xE282B0** [comment]
I took a closer look and the shims in this repo (WasmTime,WasmEdge,Wasmer) seem to work with cgroups v1.
Since I don't think it needs to be part of `containerd-shim-wasm` I created a this PR https://github.com/deislabs/containerd-wasm-shims/pull/149 to fix the deislabs shims (spin,slight,wws,lunatic) and close this issue.
