### ISSUE TITLE
runwasi logo idea

### ISSUE THREAD

**Issue by nigelpoulton** [containerd/runwasi#29]
I don't _think_ the project has a logo, so I'm proposing the following.

I'm excited about the project, but I'm not a developer, so this is me trying to contribute. The idea is **run**ning **WASI** :-D

![runwasi logo idea](https://user-images.githubusercontent.com/10812787/204770022-10790190-b381-43af-bc23-e84ebf18f9ef.png)

I won't lose any sleep if nobody likes it or is too busy to care right now.

**Comment by Mossaka** [comment]
I love this!!

**Comment by devigned** [comment]
ngl, this made me smile this morning. Well done!

**Comment by nigelpoulton** [comment]
> ngl, this made me smile this morning. Well done!

I just needed something for diagrams in a blog I wrote yesterday. It turned out pretty cool, so I thought I'd throw it out there. Glad it made you smile.

**Comment by danbugs** [comment]
I absolutely love this, @nigelpoulton~ big +1 from me!

**Comment by cpuguy83** [comment]
🤣 Amazing.

**Comment by Mossaka** [comment]
Let's make this the official logo to runwasi, sounds good? 

@devigned @cpuguy83 @danbugs

**Comment by nigelpoulton** [comment]
> Let's make this the official logo to runwasi, sounds good?
> 
> @devigned @cpuguy83 @danbugs

If we go ahead with this, which I think we should :-D 
I'm happy to provide any SVG and other formats required.

**Comment by devigned** [comment]
@nigelpoulton what do you think about adding the artwork to https://github.com/cncf/artwork with a new project for runwasi?

**Comment by nigelpoulton** [comment]
> 

Sounds good to me. I've had a quick look at the requirements and will post some quick examples of each here for comment as some require the project name either to the right, or below. Right now all I've shared is the logo part without the project name. So we'd probs just need some quick consensus on a font etc.

My initial thought was the same font as containerd, but that's a very distinctive squared off font. I'll may be lok into what WebAssembly uses.

Open to suggestions.

**Comment by benatkin** [comment]
[The official WASI logo has SI in light blue.](https://github.com/WebAssembly/WASI?tab=readme-ov-file#webassembly-system-interface)
