### ISSUE TITLE
Adding a build script to wasmer to see version information

### ISSUE THREAD

**Issue by dierbei** [containerd/runwasi#303]
Adding a build script to wasmer to see version information.

You can refer to the following example:

https://github.com/containerd/runwasi/blob/e1f9e925cf283437f3445a68e552c2d2124c0e9b/crates/containerd-shim-wasmtime/build.rs#L1-L24

https://github.com/containerd/runwasi/blob/e1f9e925cf283437f3445a68e552c2d2124c0e9b/crates/containerd-shim-wasmtime/src/lib.rs#L14-L25

**Comment by jprendes** [comment]
Fixed by #293 .
