### ISSUE TITLE
Issue with Git-Dependent Functions in Release Tarball

### ISSUE THREAD

**Issue by FerrazArthur** [containerd/runwasi#341]
Hello,

I've encountered an issue while working with the release tarball from the [containerd/runwasi ](https://github.com/containerd/runwasi) GitHub repository, specifically the release tagged as [containerd-shim-wasmer/v0.2.0](https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasmer%2Fv0.2.0).

The problem I encountered is that this release tarball contains dependencies on Git-specific functions, which made it necessary for me to manually remove these functions in order to successfully build the packages.

Here are the specifics:

    Affected Files:

    I had to remove the Git-related function "revision!()", from the following files in the release tarball:
        crates/containerd-shim-wasmedge/src/main.rs
        crates/containerd-shim-wasmtime/src/main.rs
        crates/containerd-shim-wasmer/src/main.rs

    Steps to Reproduce:

    To reproduce the issue, simply download the release tarball from the provided link and attempt to build the packages. You will encounter Git-related function dependencies.

I have Git installed on my system, as confirmed by running the following commands:
```
> which git
/usr/bin/git
```
```
> git --version
git version 2.34.1
```

I believe addressing this issue will enhance the usability and accessibility of the release tarball for a wider audience.

Thank you for your attention to this matter.

Best regards,

Arthur Ferraz

**Comment by jsturtevant** [comment]
looks like the tool is using git binary: https://docs.rs/git-version/latest/git_version/

```
These macros do not depend on libgit, but simply uses the git binary directly. So you must have git installed somewhere in your PATH.
```

**Comment by jprendes** [comment]
Yep, and the release tar files do no include the `.git` directory, which leads the macro to fail.
We need to think of a workaround.

**Comment by FerrazArthur** [comment]
> looks like the tool is using git binary: https://docs.rs/git-version/latest/git_version/
> 
> ```
> These macros do not depend on libgit, but simply uses the git binary directly. So you must have git installed somewhere in your PATH.
> ```

Interestingly, I have Git installed on my system, as confirmed by running the following commands: 
```bash
>git --version
git version 2.34.1
```
```bash
>which git
/usr/bin/git
```
Git version 2.34.1 is installed, and the 'git' binary is located at '/usr/bin/git' in my PATH.

**Comment by jprendes** [comment]
Yes, the problem is that running `git describe` outside a git repository results in an error. This is the error picked up by the `revision!` macro.
