### ISSUE TITLE
Sporadic failures in E2E CI

### ISSUE THREAD

**Issue by jprendes** [containerd/runwasi#347]
CI is sporadically failing on E2E tests, across all of them: smoke tests, kind, and k3s tests
For an example, see this run:
https://github.com/containerd/runwasi/actions/runs/6391393082/job/17346723004

**Comment by jprendes** [comment]
From the containerd logs from [this CI run](https://github.com/containerd/runwasi/actions/runs/6398602640/job/17369215846), which generated [these logs artifact](https://github.com/containerd/runwasi/suites/16843375484/artifacts/962013504)
```
[INFO] starting instance: 665173b26c87393303cfdd55a68427afc5025f083f2e6a56916d11005c02c5a1
[INFO] about to build container instance: 665173b26c87393303cfdd55a68427afc5025f083f2e6a56916d11005c02c5a1
[INFO] about to REALLY build the container instance: 665173b26c87393303cfdd55a68427afc5025f083f2e6a56916d11005c02c5a1
[INFO] cgroup manager V2 will be used
[WARN] Controller rdma is not yet implemented.
[WARN] Controller misc is not yet implemented.
[time="2023-10-03T21:33:53.554067718Z" level=info msg="StartContainer for \"33e8e760bae0ce1ed34b80d16e8e0cf187b51a641a82421fc1379a8a59526365\" returns successfully"
WARN] Controller rdma is not yet implemented.
[WARN] Controller misc is not yet implemented.
[INFO] starting instance: 25633cc2ec2915d7ab31407f5312d86a271498e784f25cd9268b8d300bf76f56
[INFO] about to build container instance: 25633cc2ec2915d7ab31407f5312d86a271498e784f25cd9268b8d300bf76f56
[INFO] about to REALLY build the container instance: 25633cc2ec2915d7ab31407f5312d86a271498e784f25cd9268b8d300bf76f56
[INFO] cgroup manager V2 will be used
[WARN] Controller rdma is not yet implemented.
[WARN] Controller misc is not yet implemented.
[WARN] Controller rdma is not yet implemented.
[WARN] Controller misc is not yet implemented.
[INFO] starting instance: c2f10adebbddfc541ac0eefbeb7382b428f9bd8c87af4fd675cbf49e7cd3bc16
[INFO] about to build container instance: c2f10adebbddfc541ac0eefbeb7382b428f9bd8c87af4fd675cbf49e7cd3bc16
[INFO] about to REALLY build the container instance: c2f10adebbddfc541ac0eefbeb7382b428f9bd8c87af4fd675cbf49e7cd3bc16
[INFO] cgroup manager V2 will be used
[WARN] Controller rdma is not yet implemented.
[WARN] Controller misc is not yet implemented.
[WARN] Controller rdma is not yet implemented.
[WARN] Controller misc is not yet implemented.
[INFO] XXXXXXXX validating container
[INFO] XXXXXXXX container executor get_or_init
[INFO] XXXXXXXX a linux container!
[WARN] intermediate process already reaped
[INFO] successfully built container instance: c2f10adebbddfc541ac0eefbeb7382b428f9bd8c87af4fd675cbf49e7cd3bc16
[INFO] container instance: c2f10adebbddfc541ac0eefbeb7382b428f9bd8c87af4fd675cbf49e7cd3bc16 has pid 5773
[INFO] XXXXXXXX executing container
[INFO] executing linux container
time="2023-10-03T21:33:53.864393966Z" level=info msg="StartContainer for \"c2f10adebbddfc541ac0eefbeb7382b428f9bd8c87af4fd675cbf49e7cd3bc16\" returns successfully"
[INFO] XXXXXXXX validating container
[INFO] XXXXXXXX container executor get_or_init
[INFO] XXXXXXXX a linux container!
[WARN] intermediate process already reaped
[INFO] successfully built container instance: 25633cc2ec2915d7ab31407f5312d86a271498e784f25cd9268b8d300bf76f56
[INFO] container instance: 25633cc2ec2915d7ab31407f5312d86a271498e784f25cd9268b8d300bf76f56 has pid 5758
[INFO] XXXXXXXX executing container
[INFO] executing linux container
```

There are 3 `starting instance: ...` corresponding to the 3 nginx linux containers.
There are 3 `[INFO] about to REALLY build the container instance: ...`, which is printed [here](https://github.com/jprendes/runwasi/blob/a0dd727c06b7a48c73ded58494e4cff4df8d3553/crates/containerd-shim-wasm/src/sys/unix/container/instance.rs#L70) just before calling `build()` on the `libcontianer`'s `ContainerBuilder`.
The call to `build()` should call the `validate(...)` method in the executor [here](https://github.com/jprendes/runwasi/blob/a0dd727c06b7a48c73ded58494e4cff4df8d3553/crates/containerd-shim-wasm/src/sys/unix/container/executor.rs#L32), however, thre are only 2 lines with `XXXXXXXX validating container`.

This means that we are getting stuck somewhere inside of the `build()` call.
@utam0k @yihuaf , do you have any clue on where in libcontainer we could be getting stuck?
Thanks!

**Comment by jsturtevant** [comment]
this might be the root cause of #322

**Comment by utam0k** [comment]
Is there anything I can help you?

**Comment by jprendes** [comment]
@utam0k , I am currently adding debugging print statements in a fork of youki, trying to find where we are stalling. If you have any pointer of good places to look at, that would be great.

**Comment by jprendes** [comment]
It looks like we are getting stuck in here: https://github.com/jprendes/youki/blob/runwasi-ci/crates/libcontainer/src/process/container_main_process.rs#L174
```
    main_receiver.wait_for_init_ready().map_err(|err| {
        tracing::error!("failed to wait for init ready: {}", err);
        err
    })?;
```

Also, it looks like we never get to the executor's `validate(...)`, which IIUC should happen in the same process where the `init_ready` should have been signaled. Will dig further.

**Comment by jprendes** [comment]
I am seeing it get stuck on this line https://github.com/jprendes/youki/blob/runwasi-ci/crates/libcontainer/src/process/container_init_process.rs#L457
```
    set_supplementary_gids(proc.user(), &args.user_ns_config, syscall.as_ref()).map_err(|err| {
        tracing::error!(?err, "failed to set supplementary gids");
        err
    })?;
```

which seems really odd to me!

**Comment by jprendes** [comment]
It never makes it past https://github.com/jprendes/youki/blob/runwasi-ci/crates/libcontainer/src/syscall/linux.rs#L494
```
if let Err(err) = setgroups(groups) {
```
where `setgroups` is `nix::unistd::setgroups`.
I wonder if this is related to `libseccomp`.

**Comment by utam0k** [comment]
@jprendes FYI: https://containers.github.io/youki/developer/debugging.html

**Comment by utam0k** [comment]
How can I reproduce this error?

**Comment by jprendes** [comment]
Here you can see the locking in the musl implementation (although in CI it's the glibc the impl we are using):
https://github.com/bminor/musl/blob/79bdacff83a6bd5b70ff5ae5eb8b6de82c2f7c30/src/linux/setgroups.c#L29
https://github.com/bminor/musl/blob/79bdacff83a6bd5b70ff5ae5eb8b6de82c2f7c30/src/thread/synccall.c#L44

**Comment by jprendes** [comment]
I am still trying to get some logs using bpftrace.
It seems that just by tracing it the failure rate gets reduced. Yay for Heisenbugs!

**Comment by jprendes** [comment]
This is interesting.
When it fails in `k3s`, as far as I can see it's in the `setgroups` call.
When it fails in `kind`, as far as I can see it's in the `setresuid` call.
Both of these libc functions use the same thread synchronization strategy.

**Comment by jprendes** [comment]
I switched my patched youki to use the raw syscall instead of the libc wrappers and I haven't seen it fail yet. I will try removing the bpftracing, as that did reduce the frequency of failures and see if that has any impact.

Using the raw syscalls is safe because the init process has only one thread when the calls are made.

**Comment by jprendes** [comment]
I wonder if this could be related 
https://sourceware.org/bugzilla/show_bug.cgi?id=26371

**Comment by jprendes** [comment]
I think that's the root cause, as youki is using a raw syscall to perform `clone3`.
https://github.com/containers/youki/blob/fee46419300114bfe92aee71945929c6aaba0a53/crates/libcontainer/src/process/fork.rs#L117

**Comment by yihuaf** [comment]
See if the investigation in this issue helps: https://github.com/containers/youki/issues/2144

**Comment by jprendes** [comment]
Thanks @yihuaf 
Please note that this is happening with glibc in these tests.
There's a glibc feature request from systemd, related to clone3 with explicit mentions of setgroups and friends.
Also, runwasi spawns multiple threads by the time youki calls clone3.

**Comment by yihuaf** [comment]
The underlying issue is calling raw syscall and then calling libc syscall becomes undefined behavior. While authors of both glibc and musl maintains this stance, in the field, `glibc` works most of the time whereas `musl` is more pronounced. If `youki` using clone3 syscall directly is the issue, may be try with the fallback path of `clone` and see if the issue persists.

> There's a glibc feature request from systemd, related to clone3 with explicit mentions of setgroups and friends.

I think the request has been there since 2020s. It will take some times :)

**Comment by jprendes** [comment]
Yeah, sorry, I don't mean to wait for glibc to provide a wrapper, it was just as a reference to the behaviour we observe being reported on glibc (not just musl).

I will give the fallback path a go. If that works, could the clone3 path be gated by a feature flag?

**Comment by jprendes** [comment]
@yihuaf @YJDoc2, even with the change from `clone3` to `clone` I'm still seeing failures. I'll investigate further.

**Comment by jprendes** [comment]
See logs here: https://github.com/containerd/runwasi/suites/17048867407/artifacts/973767783

In particular, `see containerd.log`
Debug printing corresponds to branch https://github.com/jprendes/youki/blob/runwasi-ci/crates/libcontainer/src/process/container_init_process.rs#L456

You can see `[INFO] YYYYYY libcontainer::fork >> about to do normal clone`, which means it is not using `clone3`, but `libc::clone` (debug printing from here: https://github.com/jprendes/youki/blob/runwasi-ci/crates/libcontainer/src/process/fork.rs#L60)

As before, it is getting stuck in `setgroups`.

**Comment by YJDoc2** [comment]
@jprendes can you describe a way to run this locally, so we can iterate and figure out the issue more quickly? Also, when you say that it is getting stuck, is the CI getting canceled because of timeout? As far I can think, hanging in (essentially) a syscall is strange, as it should return error right away if there was any setup/  config issue when calling. Also, for this are we using the main branch or released v0.2.0 for crates? If we are using released version, and the errors have started only recently, it can be due to some underlying env config changes too.

In the containerd logs, is the `context deadline exceeded` error due to youki not starting the container/hanging?

**Comment by jprendes** [comment]
@YJDoc2 I haven't been able to reproduce locally, although I will give that a more thorough try.

That job in CI has a 5 min tomeout, and it's getting killed after that timeout.

I believe it is not hanging on the syscall itself, but on the glibc implementation which does container a thread synchronization mechanism (aparently the setgroups kernel syscall only affects the calling thread, and glibc takes care off calling it from every thread using signaling).

Initially I thought that since youki was using a raw syscall for `clone3`, glibc didn't have a change to do house keeping and update the list of running threads in the new process, and that switching to `libc::clone` would do the trick. But after the switch it still hangs in the same place.

The logs are using a forked version adding debugging prints, based off my PR to disable `clone3`, which is based off `youki`'s main branch. But it also happens with v0.2.0 (which is why I started investigating).

I am not sure where the `context deadline exceeded` message is coming from, but I strongly believe it's caused by the hang in setgroups.

**Comment by YJDoc2** [comment]
> I haven't been able to reproduce locally, although I will give that a more thorough try.

Hey, I saw the previous conversation regarding this, that the issue is only seen on CI ; I am just asking, can you share the instructions to run the particular test/CI  things locally, so we can also try to do this and see if we can reproduce.

> That job in CI has a 5 min tomeout, and it's getting killed after that timeout.

:+1:

>The logs are using a forked version adding debugging prints, based off my PR to disable clone3, which is based off youki's main branch. But it also happens with v0.2.0 (which is why I started investigating).

:+1:

> I am not sure where the context deadline exceeded message is coming from, but I strongly believe it's caused by the hang in setgroups.

Yeah, I'd also think so. I have seen this error message (in proper crio/runc k8s) when something underlying k8s fails, such as image pulling and potentially runtime hanging up.

**Comment by jprendes** [comment]
You can try running:
```
make test/k3s-wasmedge
make test/k3s/clean
```
in a loop until it happens, that's what I was going to try :-)

**Comment by jprendes** [comment]
I made a simplified reproduction. Debugging with gdb on the halted process I get:
![image](https://github.com/containerd/runwasi/assets/2564439/31990ca2-df3b-468f-ae50-6e45de945af8)

**Comment by jprendes** [comment]
Well, it looks like clone also messes up with printing to the console.
Here's the backtrace without any printing, halted purely in setgroups
![image](https://github.com/containerd/runwasi/assets/2564439/f9b85ccb-700b-45bc-8055-f42d2d806346)

**Comment by utam0k** [comment]
Sorry I haven't had much time lately 🙇 🙇 
How about calling setgroups directly as in Go language?
It is strange that runc has not faced this problem.
https://cs.opensource.google/search?q=setgroups&sq=&ss=go%2Fx%2Fsys

Also, bpftrace or whatever, but I want to make sure first that the setgroups system call is actually called.

**Comment by jprendes** [comment]
@utam0k calling setgroups / setresgid / setresuid directly would workaround the issue.
I am slightly concerned because in normal youki / runc, we soon call execve, which starts a clean process.
In the case of runwasi, we don't, we keep running on the same tainted process.
From [nix::clone](https://docs.rs/nix/latest/nix/sched/fn.clone.html) and [nix::fork](https://docs.rs/nix/latest/nix/unistd/fn.fork.html), even memory allocation might be unsafe after the `clone` call (I assume it's platform / variant dependent).
