### ISSUE TITLE
Provide the binary file " container ship wasm * " for runwasi

### ISSUE THREAD

**Issue by Avey777** [containerd/runwasi#528]
containerd-shim-wasmtime-x86_64.tar.gz

For some reason, I failed to build from the source code on my end! Since version 0.4.0, runwasi has not provided compiled binary files. We hope that each version will provide binary files for everyone to download and obtain

**Comment by jsturtevant** [comment]
Although we tagged the versions for the shims yesterday we don't have a Github Release for the shims yet, only the library for [building the shims](https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasm%2Fv0.5.0). 

The shim pipeline failed yesterday and we are working on fixing it (https://github.com/containerd/runwasi/issues/527).  Once it is fixed we should have a Github Release with the binaries in it.

**Comment by jsturtevant** [comment]
Thanks for the patience, we have released the binaries for the shims

https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasmtime%2Fv0.4.0
https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasmer%2Fv0.4.0
https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasmedge%2Fv0.4.0
