### ISSUE TITLE
compile-error 

### ISSUE THREAD

**Issue by erkules** [containerd/runwasi#566]
Not a lot to say.

Kernel Linux somisan 6.7.5-x64v3-xanmod1 #0~20240216.gf29bf01 SMP PREEMPT_DYNAMIC Fri Feb 16 20:35:14 UTC x86_64 x86_64 x86_64 GNU/Linux

~~~
$ make build
cargo build --target=x86_64-unknown-linux-gnu --target-dir=./target/ -p containerd-shim-wasm  
   Compiling libcontainer v0.3.2
error[E0599]: no method named `get_notify_fd` found for struct `ScmpFilterContext` in the current scope
   --> /home/erkan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libcontainer-0.3.2/src/seccomp/mod.rs:270:17
    |
270 |             ctx.get_notify_fd()
    |                 ^^^^^^^^^^^^^ method not found in `ScmpFilterContext`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `libcontainer` (lib) due to previous error
make: *** [Makefile:72: build-wasm] Error 101

~~~

**Comment by Mossaka** [comment]
Related: https://github.com/containerd/runwasi/issues/486

Particularly this comment might help: https://github.com/containerd/runwasi/issues/486#issuecomment-1953869319

**Comment by jprendes** [comment]
This https://github.com/containerd/runwasi/issues/486#issuecomment-1974609829 might also help.

**Comment by erkules** [comment]
While ` cargo clean -p libseccomp -p libseccomp-sys` resulted in the same error.
`make CARGO=cross build` worked.

thx @all
