### ISSUE TITLE
ctr: failed to create shim task, wasmtime can't handle spec?

### ISSUE THREAD

**Issue by matsbror** [containerd/runwasi#637]
I have compiled and installed the wasmtime shim (and wasmedge and wasmer), and I am able to run a wasm module using docker:

```
docker run --rm --runtime io.containerd.runtime.wasmtime.v1 matsbror/serwasm2:0.1
```

However, I would like to run it directly using `ctr` if possible, but I get this error:

```
sudo ctr run --rm --runtime io.containerd.runtime.wasmtime.v1 docker.io/matsbror/serwasm2:0.1 myapp bogus
ctr: failed to create shim task: Others("exec process failed with error error in executing process : wasmtime executor can't handle spec"): unknown
```

I can run a spin app directly using `ctr` with the spin shim from spinkube.

**Comment by Mossaka** [comment]
It's hard to tell what's going on with this error, and perhaps it would be helpful to add `containerd` logs. 

If you are running containerd as a service in Linux, you can check containerd logs by `journalctl -u containerd`. It seems like this error msg is from https://github.com/Mossaka/runwasi/blob/main/crates/containerd-shim-wasm/src/sys/unix/container/executor.rs#L40

**Comment by dvperez-grad** [comment]
Same error here but inside a pod of Kubernetes (Kind) and using WasmEdge. Kubectl logs empty. 

![imagen](https://github.com/user-attachments/assets/0c3e1ece-2269-48e0-8c4e-39f5bba0c340)

Any ideas?

**Comment by Mossaka** [comment]
The error message should be more explicity after #655.
