### ISSUE TITLE
Instance.wait() call semantics are weird

### ISSUE THREAD

**Issue by cpuguy83** [containerd/runwasi#67]
The `Instance` trait has a `wait` function which is used to wait for the instance to exit.
Due to issues with threading and lifetimes the call currently takes a channel sender.

Ideally any sort of async behavior should be handled by the caller (e.g. wrap it in a thread and handle the channels at the call site rather than expecting the implementation to).
Lifetimes of the type parameters on Instance make this a little more problematic and I am currently hesitant to use a `'static` lifetime (required by thread::spawn).

**Comment by Mossaka** [comment]
The scoped spawn in `std::thread::scope` does not require a `'static` lifetime, maybe it's worth checking out. 

https://doc.rust-lang.org/std/thread/fn.scope.html

**Comment by cpuguy83** [comment]
`std::thread::scope` is useful for scatter+gather scenarios only because it automatically joins any spawned threads when the scope is dropped.

For this use case it will end up blocking the us from returning because it will have to wait for the scope to finish.
We may be able to work around this if we keep the scope around until the instance is deleted, but I think this will require significant rework as we probably only actually want a single thread scope for this.

**Comment by cpuguy83** [comment]
Sorry no, that doesn't work... the scope becomes out of scope as soon as `thread::scope()` returns.
