### ISSUE TITLE
Release a new version for all the shim binaries: Wasmtime, WasmEdge, Wasmer, Wamr

### ISSUE THREAD

**Issue by Mossaka** [containerd/runwasi#713]
@andreiltd has done some amazing work in the wasmtime shim: https://github.com/containerd/runwasi/pull/691, https://github.com/containerd/runwasi/pull/700 and https://github.com/containerd/runwasi/pull/705. I think it's a good time to release a new version for the wasmtime shim binary and update the docs on how to use wasi-http with wasmtime shim in containerd and k8s. 

- [x] #728 
- [x] #729
- [x] bump wasmedge, wasmer

**Comment by jprendes** [comment]
If we wait a bit we might be able to bump wasmedge and wasmer as well

**Comment by Mossaka** [comment]
All the shim binaries are released:
[wasmtime v0.5.0](https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasmtime%2Fv0.5.0)
[wasmedge v0.5.0](https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasmedge%2Fv0.5.0)
[wasmer v0.5.0](https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasmer%2Fv0.5.0)
[wamr v0.1.0](https://github.com/containerd/runwasi/releases/tag/containerd-shim-wamr%2Fv0.1.0)

you can use the following command to verify the binary signature:
```console 
cosign verify-blob \
    --signature containerd-shim-wasmtime-v1.sig \
    --certificate containerd-shim-wasmtime-v1.pem \
    --certificate-identity https://github.com/containerd/runwasi/.github/workflows/action-build.yml@refs/heads/main \
    --certificate-oidc-issuer https://token.actions.githubusercontent.com/ \
    containerd-shim-wasmtime-v1

Verified OK
```
